---
- name: Install dependencies for Tarsnap
  apt: pkg={{item}} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
    - build-essential

- name: Download the current tarsnap code signing key
  get_url:
    url=https://www.tarsnap.com/tarsnap-signing-key.asc
    dest="{{base_dir}}/tarsnap-signing-key.asc"

- name: Add the tarsnap code signing key to your list of keys
  command:
    gpg --import tarsnap-signing-key.asc
    chdir={{base_dir}}

- name: Download tarsnap SHA file
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-sigs-{{tarsnap_version}}.asc"
    dest="{{base_dir}}/tarsnap-sigs-{{tarsnap_version}}.asc"

- name: Make the command that gets the current sha
  template:
    src=getSha.sh
    dest="{{base_dir}}/getSha.sh"
    mode=0755

- name: get the SHA256sum for this tarsnap release
  command:
    ./getSha.sh
    chdir={{base_dir}}
  register: tarsnap_sha

- name: Download Tarsnap source
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-autoconf-{{tarsnap_version}}.tgz"
    dest="{{base_dir}}/tarsnap-autoconf-{{tarsnap_version}}.tgz"
    sha256sum={{tarsnap_sha.stdout_lines[0]}}

- name: Decompress Tarsnap source
  command:
    tar xzf "{{base_dir}}/tarsnap-autoconf-{{tarsnap_version}}.tgz"
    chdir={{base_dir}}
    creates="{{base_dir}}/tarsnap-autoconf-{{tarsnap_version}}/COPYING"

- name: Configure Tarsnap for local build
  command:
    ./configure
    chdir="{{base_dir}}/tarsnap-autoconf-{{tarsnap_version}}"
    creates="{{base_dir}}/tarsnap-autoconf-{{tarsnap_version}}/Makefile"

- name: Build and install Tarsnap
  command:
    make all install clean
    chdir="{{base_dir}}/tarsnap-autoconf-{{tarsnap_version}}"
    creates=/usr/local/bin/tarsnap

