---
- name: Check if Tarsnap {{ tarsnap_version }} is installed
  shell: tarsnap --version | grep {{ tarsnap_version }} --color=never
  register: tarnsap_installed
  changed_when: "tarnsap_installed.stderr != ''"
  ignore_errors: yes

- name: build tarsnap from source
  import_tasks: build-from-source.yml
  when: (tarnsap_installed|failed) and (ansible_os_family != "Debian")

- name: install tarsnap debian packages because tarsnap recommends using them
  import_tasks: use-official-packages.yml
  when: (tarnsap_installed|failed) and (ansible_os_family == "Debian")

- name: Copy Tarsnap key file into place
  copy:
    src=root_tarsnap.key
    dest="{{base_dir}}/tarsnap.key"
    owner={{install_user}}
    group={{install_user}}
    mode=0644

- name: Create Tarsnap cache directory
  file:
    state=directory
    path=/usr/tarsnap-cache

- name: Install Tarsnap configuration file
  template:
    src=tarsnaprc
    dest="{{base_dir}}/.tarsnaprc"
    mode="644"

- name: Install Tarsnap backup handler script
  template:
    src=tarsnap.sh
    dest="{{base_dir}}/tarsnap.sh"
    mode="755"

- name: Install nightly Tarsnap-generations cronjob
  cron:
    name="Tarsnap backup"
    hour="23"
    minute="0"
    job="sh {{base_dir}}/tarsnap.sh >> /var/log/tarsnap.log"
